from class33mascotas import Mascota
print("Pedir datos de mascota")
mascota1=Mascota()
print("Dame el nombre de la mascota numero 1")
mascota1.nombre=input()
print("Dame el tipo de mascota 1")
mascota1.tipo=input()
print("Dame el año de nacimeinto 1")
mascota1.yearNacimento=int(input())
print("Dame el año de adopcion 1")
print("la edad de la mascota nuemro 1", "es", str(mascota1.getEdad()))
mascota2=Mascota()
print("Dame el nombre de la mascota numero 2")
mascota2.nombre=input()
print("Dame el tipo de mascota 2")
mascota2.tipo=input()
print("Dame el año de nacimeinto 2")
mascota2.yearNacimento=int(input())
print("Dame el año de adopcion 2")
print("la edad de la mascota nuemro 2"), "es", str(mascota2.getEdad())
mascota3=Mascota()
print("Dame el nombre de la mascota numero 3")
mascota3.nombre=input()
print("Dame el tipo de mascota 3")
mascota3.tipo=input()
print("Dame el año de nacimeinto 3")
mascota3.yearNacimento=int(input())
print("Dame el año de adopcion 3")
print("la edad de la mascota nuemro 3"), "es", str(mascota3.getEdad())
