select * from EMP;

select * from DEPT;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO where DEPT.LOC='SEVILLA';

select DOCTOR.APELLIDO, DOCTOR.ESPECIALIDAD,HOSPITAL.NOMBRE, HOSPITAL.DIRECCION 
from DOCTOR 
inner join HOSPITAL 
on DOCTOR.HOSPITAL_COD=HOSPITAL.HOSPITAL_COD 
order by DOCTOR.ESPECIALIDAD;

select count(*) as NUMEROPERSONAS, DEPT.DNOMBRE from EMP inner join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO group by DEPT.DNOMBRE;
select distinct DEPT_NO from EMP;

select * from DEPT;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP full join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP left join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;

select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP right join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;
--
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP inner join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP left join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP right join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP full join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO;
select EMP.APELLIDO, EMP.OFICIO, DEPT.DNOMBRE, DEPT.LOC from EMP cross join DEPT;
--
select sum(PLANTILLA.SALARIO) as TOTALSALARIO, HOSPITAL.NOMBRE from HOSPITAL inner join PLANTILLA on HOSPITAL.HOSPITAL_COD=PLANTILLA.HOSPITAL_COD group by HOSPITAL.NOMBRE;
select count(EMP.EMP_NO) as NUMEROPERSONAS, DEPT.LOC from EMP right join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO group by DEPT.LOC;
--
select PLANTILLA.APELLIDO, PLANTILLA.FUNCION, 
HOSPITAL.NOMBRE, HOSPITAL.DIRECCION, 
SALA.NOMBRE 
from PLANTILLA 
inner join HOSPITAL  
on PLANTILLA.HOSPITAL_COD=HOSPITAL.HOSPITAL_COD
inner join SALA
on HOSPITAL.HOSPITAL_COD=SALA.HOSPITAL_COD 
and PLANTILLA.SALA_COD=SALA.SALA_COD order by PLANTILLA.APELLIDO;
select * from PLANTILLA;