--
select EMP.APELLIDO, EMP.OFICIO, EMP.SALARIO, DEPT.DEPT_NO, DEPT.DNOMBRE 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO 
where EMP.SALARIO >300000;
--
select SALA.NOMBRE as NOMBRESALA, HOSPITAL.NOMBRE as NOMBREHOSPITAL 
from HOSPITAL 
inner join SALA on HOSPITAL.HOSPITAL_COD=SALA.HOSPITAL_COD;
--
select count(EMP.EMP_NO) as NUMEROPERSONAS, DEPT.LOC 
from EMP inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO 
group by DEPT.LOC;
--
select count(EMP.EMP_NO) as NUMEROPERSONAS, DEPT.DNOMBRE, EMP.OFICIO 
from EMP 
inner join DEPT on EMP.DEPT_NO=DEPT.DEPT_NO 
group by EMP.OFICIO, DEPT.DNOMBRE 
order by DEPT.DNOMBRE;
--
select count(SALA.SALA_COD) as NUMERODESALAS, HOSPITAL.NOMBRE as HOSPITAL, SALA.NOMBRE as SALA 
from HOSPITAL 
inner join SALA 
on HOSPITAL.HOSPITAL_COD=SALA.HOSPITAL_COD 
group by HOSPITAL.NOMBRE, SALA.NOMBRE;
--
select count(EMP.EMP_NO) as ALTAS, DEPT.DNOMBRE, EMP.FECHA_ALT 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO 
where EMP.FECHA_ALT>'01/01/1997' and EMP.FECHA_ALT<'01/01/1999' 
group by DEPT.DNOMBRE, EMP.FECHA_ALT;
--
select count(EMP.EMP_NO) as NUMEROPERSONAS, DEPT.LOC 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO 
having count(EMP.EMP_NO)>=4 
group by DEPT.LOC;
--
select avg(SALARIO) as MEDIASALARIA, DEPT.LOC 
from EMP 
inner join DEPT 
on EMP.DEPT_NO=DEPT.DEPT_NO 
group by DEPT.LOC;